"""empty message

Revision ID: 666c7d9fc4d0
Revises: 
Create Date: 2025-08-24 23:10:51.720511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '666c7d9fc4d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('follower')
    op.drop_table('media')
    op.drop_table('post')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('firstname')
        batch_op.drop_column('lastname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('firstname', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    op.create_table('post',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('post_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='post_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='post_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('media',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', postgresql.ENUM('image', 'video', name='media_type'), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('media_post_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('media_pkey'))
    )
    op.create_table('follower',
    sa.Column('user_from_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_to_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_from_id'], ['user.id'], name=op.f('follower_user_from_id_fkey')),
    sa.ForeignKeyConstraint(['user_to_id'], ['user.id'], name=op.f('follower_user_to_id_fkey')),
    sa.PrimaryKeyConstraint('user_from_id', 'user_to_id', name=op.f('follower_pkey'))
    )
    op.create_table('comment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('comment_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('comment_author_id_fkey')),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('comment_post_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('comment_pkey'))
    )
    # ### end Alembic commands ###
